<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OptionInfer>On</OptionInfer>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Drawing.Skia" Version="24.2.13" />
    <PackageReference Include="DevExpress.Pdf.Drawing" Version="24.2.13" />
    <PackageReference Include="DevExpress.Document.Processor" Version="24.2.13" />
  </ItemGroup>
</Project>